 server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

     # Увеличиваем максимальный размер загружаемого файла до 200 МБ
    client_max_body_size 200M;


    # -------------------
    # Включаем Gzip и Brotli
    # -------------------
    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json text/xml text/html;
    gzip_min_length 256;
    gzip_vary on;

    # -------------------

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_pass php:9000;

        # Прокидываем протокол HTTPS от Traefik в Laravel
        fastcgi_param HTTPS $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_REAL_IP $remote_addr;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ /\.ht {
        deny all;
    }
}
